db:
  build: scripts/dockerfiles/opd_postgres
  restart: always

web:
  build: .
  restart: always
  command: ./run.sh
  volumes:
    - .:/code
  ports:
    - "18080:80"
  links:
    - db:opd_postgres
