
# PostgreSQL 9.4 ------------------------------------------------------------
# See https://hub.docker.com/_/postgres/

FROM postgres:9.4
MAINTAINER Daniel Fowler <me@danfowler.net>
RUN localedef -i en_US -c -f UTF-8 -A /usr/share/locale/locale.alias en_US.UTF-8
ENV LANG en_US.utf8
