# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-16 01:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('browser', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gs1_gpc_hier',
            fields=[
                ('GPC_S_CD', models.CharField(max_length=8)),
                ('GPC_F_CD', models.CharField(max_length=8)),
                ('GPC_C_CD', models.CharField(max_length=8)),
                ('GPC_B_CD', models.CharField(max_length=8, primary_key=True, serialize=False)),
            ],
        ),
    ]
