# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-03 10:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('browser', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gtin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('GTIN_CD', models.CharField(max_length=13)),
                ('GTIN_LEVEL_CD', models.IntegerField(default=0)),
                ('GCP_CD', models.CharField(max_length=13)),
                ('BSIN', models.CharField(max_length=6)),
                ('GPC_S_CD', models.CharField(max_length=8)),
                ('GPC_F_CD', models.CharField(max_length=8)),
                ('GPC_C_CD', models.CharField(max_length=8)),
                ('GPC_B_CD', models.CharField(max_length=8)),
                ('GTIN_NM', models.CharField(max_length=255)),
                ('PRODUCT_LINE', models.CharField(max_length=255)),
                ('M_G', models.FloatField(default=0)),
                ('M_OZ', models.FloatField(default=0)),
                ('M_ML', models.FloatField(default=0)),
                ('M_FLOZ', models.FloatField(default=0)),
                ('M_ABV', models.FloatField(default=0)),
                ('M_ABW', models.FloatField(default=0)),
                ('PKG_UNIT', models.IntegerField(default=0)),
                ('PKG_TYPE_CD', models.IntegerField(default=0)),
                ('REF_CD', models.CharField(max_length=255)),
                ('SOURCE', models.CharField(max_length=255)),
                ('IMG', models.IntegerField(default=0)),
            ],
        ),
        migrations.RemoveField(
            model_name='choice',
            name='question',
        ),
        migrations.DeleteModel(
            name='Choice',
        ),
        migrations.DeleteModel(
            name='Question',
        ),
    ]
