# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-03 10:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('browser', '0002_auto_20160203_1840'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gtin',
            name='id',
        ),
        migrations.AlterField(
            model_name='gtin',
            name='GTIN_CD',
            field=models.CharField(max_length=13, primary_key=True, serialize=False),
        ),
    ]
