# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-04 03:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('browser', '0004_brand'),
    ]

    operations = [
        migrations.CreateModel(
            name='Nutrition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('GTIN_CD', models.CharField(max_length=13)),
                ('INGREDIENTS', models.TextField(blank=True, null=True)),
                ('SERV_SIZE_G', models.FloatField(default=0)),
                ('SERV_SIZE_ML', models.FloatField(default=0)),
                ('SERV_CT', models.FloatField(default=0)),
                ('CAL', models.FloatField(default=0)),
                ('CAL_FROM_FAT', models.FloatField(default=0)),
                ('TOT_FAT_G', models.FloatField(default=0)),
                ('TOT_FAT_DV', models.FloatField(default=0)),
                ('SAT_FAT_G', models.FloatField(default=0)),
                ('SAT_FAT_DV', models.FloatField(default=0)),
                ('TRANS_FAT_G', models.FloatField(default=0)),
                ('CHOL_MG', models.FloatField(default=0)),
                ('CHOL_DV', models.FloatField(default=0)),
                ('SOD_MG', models.FloatField(default=0)),
                ('SOD_DV', models.FloatField(default=0)),
                ('POT_MG', models.FloatField(default=0)),
                ('POT_DV', models.FloatField(default=0)),
                ('TOT_CARB_G', models.FloatField(default=0)),
                ('TOT_CARB_DV', models.FloatField(default=0)),
                ('DIET_FIBER_G', models.FloatField(default=0)),
                ('DIET_FIBER_DV', models.FloatField(default=0)),
                ('SUGARS_G', models.FloatField(default=0)),
                ('PROTEIN_G', models.FloatField(default=0)),
                ('VITAMIN_A', models.FloatField(default=0)),
                ('VITAMIN_C', models.FloatField(default=0)),
                ('CALCIUM', models.FloatField(default=0)),
                ('IRON', models.FloatField(default=0)),
                ('SOURCE', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
