# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-04 03:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('browser', '0005_nutrition'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nutrition',
            name='id',
        ),
        migrations.AlterField(
            model_name='nutrition',
            name='GTIN_CD',
            field=models.CharField(max_length=13, primary_key=True, serialize=False),
        ),
    ]
