# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-04 03:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('browser', '0006_auto_20160204_1131'),
    ]

    operations = [
        migrations.AddField(
            model_name='nutrition',
            name='SYNC_DT',
            field=models.DateField(blank=True, null=True),
        ),
    ]
