# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-04 04:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('browser', '0007_nutrition_sync_dt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gtin',
            name='BSIN',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='browser.Brand'),
        ),
        migrations.AlterField(
            model_name='gtin',
            name='GCP_CD',
            field=models.CharField(blank=True, max_length=13, null=True),
        ),
        migrations.AlterField(
            model_name='gtin',
            name='GPC_B_CD',
            field=models.CharField(blank=True, max_length=8, null=True),
        ),
        migrations.AlterField(
            model_name='gtin',
            name='GPC_C_CD',
            field=models.CharField(blank=True, max_length=8, null=True),
        ),
        migrations.AlterField(
            model_name='gtin',
            name='GPC_F_CD',
            field=models.CharField(blank=True, max_length=8, null=True),
        ),
        migrations.AlterField(
            model_name='gtin',
            name='GPC_S_CD',
            field=models.CharField(blank=True, max_length=8, null=True),
        ),
        migrations.AlterField(
            model_name='gtin',
            name='GTIN_LEVEL_CD',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='gtin',
            name='GTIN_NM',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='gtin',
            name='IMG',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='gtin',
            name='M_ABV',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='gtin',
            name='M_ABW',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='gtin',
            name='M_FLOZ',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='gtin',
            name='M_G',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='gtin',
            name='M_ML',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='gtin',
            name='M_OZ',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='gtin',
            name='PKG_TYPE_CD',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='gtin',
            name='PKG_UNIT',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='gtin',
            name='PRODUCT_LINE',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='gtin',
            name='REF_CD',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='gtin',
            name='SOURCE',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
