# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-04 04:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('browser', '0008_auto_20160204_1225'),
    ]

    operations = [
        migrations.CreateModel(
            name='BrandType',
            fields=[
                ('BRAND_TYPE_CD', models.IntegerField(primary_key=True, serialize=False)),
                ('BRAND_TYPE_NM', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='brand',
            name='BRAND_LINK',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='brand',
            name='BRAND_TYPE_CD',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='browser.BrandType'),
        ),
    ]
