# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-04 05:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('browser', '0010_auto_20160204_1302'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gs1gpc',
            name='GPC_CD',
            field=models.CharField(max_length=20, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='gs1gpc',
            name='GPC_LANG',
            field=models.CharField(max_length=3),
        ),
        migrations.AlterField(
            model_name='gtin',
            name='GPC_B_CD',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='GPC_B_CD', to='browser.GS1gpc'),
        ),
        migrations.AlterField(
            model_name='gtin',
            name='GPC_C_CD',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='GPC_C_CD', to='browser.GS1gpc'),
        ),
        migrations.AlterField(
            model_name='gtin',
            name='GPC_F_CD',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='GPC_F_CD', to='browser.GS1gpc'),
        ),
        migrations.AlterField(
            model_name='gtin',
            name='GPC_S_CD',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='GPC_S_CD', to='browser.GS1gpc'),
        ),
    ]
