# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-04 05:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('browser', '0011_auto_20160204_1311'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='gs1gpc',
            unique_together=set([]),
        ),
    ]
