# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-04 06:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('browser', '0013_brandowner'),
    ]

    operations = [
        migrations.CreateModel(
            name='GS1gcp',
            fields=[
                ('GCP_CD', models.CharField(max_length=13, primary_key=True, serialize=False)),
                ('GLN_CD', models.CharField(max_length=13)),
                ('GLN_NM', models.CharField(max_length=255)),
                ('GLN_ADDR_02', models.CharField(max_length=38)),
                ('GLN_ADDR_03', models.CharField(max_length=38)),
                ('GLN_ADDR_04', models.CharField(max_length=38)),
                ('GLN_ADDR_POSTALCODE', models.CharField(max_length=38)),
                ('GLN_ADDR_CITY', models.CharField(max_length=38)),
                ('GLN_COUNTRY_ISO_CD', models.CharField(max_length=38)),
                ('CONTACT_NAME', models.CharField(max_length=38)),
                ('CONTACT_TEL', models.CharField(max_length=255)),
                ('CONTACT_HOTLINE', models.CharField(blank=True, max_length=255, null=True)),
                ('CONTACT_FAX', models.CharField(max_length=255)),
                ('CONTACT_MAIL', models.CharField(max_length=255)),
                ('CONTACT_WEB', models.CharField(max_length=255)),
                ('GLN_LAST_CHANGE', models.CharField(max_length=10)),
                ('GLN_PROVIDER', models.CharField(max_length=13)),
                ('SEARCH_GTIN_CD', models.CharField(max_length=13)),
                ('GEPIR_GCP_CD', models.CharField(max_length=13)),
                ('ADD_PARTY_ID', models.CharField(max_length=13)),
                ('RETURN_CODE', models.CharField(max_length=3)),
                ('SOURCE', models.CharField(max_length=100)),
                ('SYNC_DT', models.DateField(blank=True, null=True)),
            ],
        ),
    ]
