# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-04 07:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('browser', '0014_gs1gcp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gtin',
            name='GCP_CD',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='browser.GS1gcp'),
        ),
    ]
