# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-04 08:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('browser', '0015_auto_20160204_1558'),
    ]

    operations = [
        migrations.CreateModel(
            name='GS1gcpRc',
            fields=[
                ('RETURN_CODE', models.CharField(max_length=3, primary_key=True, serialize=False)),
                ('RETURN_NAME', models.CharField(max_length=255)),
                ('ORIGIN', models.CharField(max_length=255)),
            ],
        ),
    ]
