# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-11 13:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('browser', '0017_auto_20160204_1626'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gtin',
            name='BSIN',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
        migrations.AlterField(
            model_name='gtin',
            name='GCP_CD',
            field=models.CharField(blank=True, max_length=13, null=True),
        ),
        migrations.AlterField(
            model_name='gtin',
            name='GPC_B_CD',
            field=models.CharField(blank=True, max_length=8, null=True),
        ),
        migrations.AlterField(
            model_name='gtin',
            name='GPC_C_CD',
            field=models.CharField(blank=True, max_length=8, null=True),
        ),
        migrations.AlterField(
            model_name='gtin',
            name='GPC_F_CD',
            field=models.CharField(blank=True, max_length=8, null=True),
        ),
        migrations.AlterField(
            model_name='gtin',
            name='GPC_S_CD',
            field=models.CharField(blank=True, max_length=8, null=True),
        ),
        migrations.AlterField(
            model_name='gtin',
            name='GTIN_LEVEL_CD',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='gtin',
            name='IMG',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='gtin',
            name='M_ABV',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='gtin',
            name='M_ABW',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='gtin',
            name='M_FLOZ',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='gtin',
            name='M_G',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='gtin',
            name='M_ML',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='gtin',
            name='M_OZ',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='gtin',
            name='PKG_TYPE_CD',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='gtin',
            name='PKG_UNIT',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
