# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-12 13:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('browser', '0019_auto_20160212_2103'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gtin',
            name='M_ABV',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='gtin',
            name='M_ABW',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='gtin',
            name='M_FLOZ',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='gtin',
            name='M_G',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='gtin',
            name='M_ML',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='gtin',
            name='M_OZ',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='gtin',
            name='PKG_TYPE_CD',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
