# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-12 14:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('browser', '0020_auto_20160212_2104'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nutrition',
            name='GTIN_CD',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='browser.Gtin'),
        ),
    ]
