# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-12 14:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('browser', '0021_auto_20160212_2249'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nutrition',
            name='CAL',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='nutrition',
            name='CALCIUM',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='nutrition',
            name='CAL_FROM_FAT',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='nutrition',
            name='CHOL_DV',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='nutrition',
            name='CHOL_MG',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='nutrition',
            name='DIET_FIBER_DV',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='nutrition',
            name='DIET_FIBER_G',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='nutrition',
            name='IRON',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='nutrition',
            name='POT_DV',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='nutrition',
            name='POT_MG',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='nutrition',
            name='PROTEIN_G',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='nutrition',
            name='SAT_FAT_DV',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='nutrition',
            name='SAT_FAT_G',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='nutrition',
            name='SERV_CT',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='nutrition',
            name='SERV_SIZE_G',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='nutrition',
            name='SERV_SIZE_ML',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='nutrition',
            name='SOD_DV',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='nutrition',
            name='SOD_MG',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='nutrition',
            name='SUGARS_G',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='nutrition',
            name='TOT_CARB_DV',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='nutrition',
            name='TOT_CARB_G',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='nutrition',
            name='TOT_FAT_DV',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='nutrition',
            name='TOT_FAT_G',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='nutrition',
            name='TRANS_FAT_G',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='nutrition',
            name='VITAMIN_A',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='nutrition',
            name='VITAMIN_C',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
