# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-15 00:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('browser', '0022_auto_20160212_2252'),
    ]

    operations = [
        migrations.CreateModel(
            name='Search',
            fields=[
                ('GTIN_CD', models.CharField(max_length=13, primary_key=True, serialize=False)),
                ('SEARCH_NB', models.IntegerField(default=1)),
            ],
        ),
    ]
