# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-15 03:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('browser', '0023_search'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BrandOwner',
            new_name='Brand_owner',
        ),
        migrations.RenameModel(
            old_name='BrandType',
            new_name='Brand_type',
        ),
        migrations.RenameModel(
            old_name='GS1gcp',
            new_name='Gs1_gcp',
        ),
        migrations.RenameModel(
            old_name='GS1gcpRc',
            new_name='Gs1_gcp_rc',
        ),
        migrations.RenameModel(
            old_name='GS1gpc',
            new_name='GS1_gpc',
        ),
    ]
